--in the begining...
CREATE DATABASE QAP3a;

CREATE TABLE product(
	product_id SERIAL PRIMARY KEY
	,product_name VARCHAR(60) NOT NULL
	,product_description VARCHAR NOT NULL
	,product_price NUMERIC(10, 2) NOT NULL
	,product_image VARCHAR
	,category_id INTEGER NOT NULL
	,FOREIGN KEY (category_id) REFERENCES category(category_id)	
);

CREATE TABLE category(
	category_id SERIAL PRIMARY KEY
	,category_name VARCHAR(60) NOT NULL
	,category_description VARCHAR NOT NULL
	,category_image VARCHAR
);

--category creation
INSERT INTO category (category_name, category_description, category_image)
VALUES ('Smart Home Electronics', 'Welcome to our Smart Home Electronics category, where you''ll find the latest and most innovative electronic devices to transform your home into a modern, connected space. Explore a wide selection of smart devices designed to simplify your life, enhance security, and improve energy efficiency. From smart speakers with AI-powered voice assistants to intelligent thermostats and automated lighting systems, our collection offers cutting-edge solutions for a smarter, more convenient home. Embrace the future of electronics and create a seamless, intelligent living environment with our Smart Home Electronics today!', '/images/category-electronics(michal-bajus-P9LTNN1GJqk-unsplash).jpg');

INSERT INTO category (category_name, category_description, category_image)
VALUES ('Men''s Fashion', 'Welcome to our Men''s Fashion category, where style meets sophistication for the modern gentleman. Discover a carefully curated selection of trendy and timeless clothing and accessories, designed to elevate your wardrobe to new heights. From classic suits and tailored shirts for formal occasions to casual-chic jeans, t-shirts, and sneakers for everyday wear, we have a wide range of fashion pieces to suit every taste and lifestyle. Whether you''re looking to make a bold statement or embrace understated elegance, our Men''s Fashion collection offers the latest trends and wardrobe essentials to express your unique sense of style. Step into the world of refined fashion and elevate your look with our Men''s Fashion collection today!', '/images/category-mens-fashion(david-lezcano-NfZiOJzZgcg-unsplash).jpg');

INSERT INTO category (category_name, category_description, category_image)
VALUES ('Women''s Fashion', 'Welcome to our Women''s Fashion category, where style meets empowerment, and individuality takes center stage. Explore a diverse and inspiring collection of clothing and accessories, thoughtfully curated to celebrate the essence of femininity. From elegant dresses that exude confidence to comfortable and chic casual wear, we offer a wide array of fashion pieces that cater to every occasion and personality. Embrace the latest trends or discover timeless classics that stand the test of time. Whether you''re seeking vibrant colors and bold patterns or prefer the elegance of simplicity, our Women''s Fashion collection empowers you to express your unique identity through fashion. Embrace your individuality, radiate confidence, and step into the world of limitless possibilities with our Women''s Fashion collection today!', '/images/category-womens-fashion(laura-chouette-W-7k72ThEr0-unsplash).jpg');

INSERT INTO category (category_name, category_description, category_image)
VALUES ('Girl''s Fashion', 'Welcome to our Girls'' Fashion category, where creativity meets playfulness and style knows no bounds. Explore a delightful collection of clothing and accessories, specially curated to inspire young fashionistas and celebrate their individuality. From adorable dresses that sparkle with joy to comfortable and trendy everyday wear, we offer a wide array of fashion pieces for girls of all ages. Discover vibrant colors, whimsical patterns, and charming designs that reflect the spirit of childhood and let young hearts express themselves with confidence. Whether dressing up for a special occasion or exploring new adventures, our Girls'' Fashion collection ensures every outfit is a delightful expression of personality and fun. Embrace the magic of childhood fashion and dress your little ones in joy with our Girls'' Fashion collection today!', '/images/category-girls-fashion(junko-nakase-Q-72wa9-7Dg-unsplash).jpg');

INSERT INTO category (category_name, category_description, category_image)
VALUES ('Boy''s Fashion', 'Welcome to our Boys'' Fashion category, where adventure meets comfort and young minds embrace style with enthusiasm. Explore an exciting collection of clothing and accessories, handpicked to inspire young boys and amplify their sense of adventure. From cool graphic tees and rugged jeans to cozy hoodies and sporty footwear, our Boys'' Fashion collection offers a diverse range of trendy and practical choices. Let them explore the world in outfits that match their curiosity and energy, whether it''s for playdates, school days, or family outings. Discover sturdy and reliable clothing that keeps up with every adventure and fosters a sense of confidence and independence. Embrace the spirit of boyhood and dress your young explorers with flair and comfort with our Boys'' Fashion collection today!', '/images/category-boys-fashion(mnz-ToLMORRb97Q-unsplash).jpg');

INSERT INTO category (category_name, category_description, category_image)
VALUES

-- Men's Fashion (5 to start)
INSERT INTO product (product_name, product_description, product_price, product_image, category_id)
VALUES ('"Ocean Breeze" Men''s Shorts', 'Introducing our "Ocean Breeze" Men''s Shorts, the epitome of casual summer wear with a touch of fancy flair. Embrace the cool and refreshing shades of blue, reminiscent of a tranquil ocean paradise. These shorts feature a unique design pattern that effortlessly blends creativity and style, giving you a standout look that''s perfect for any relaxed summer occasion. Crafted from lightweight and breathable fabric, our "Ocean Breeze" Men''s Shorts offer utmost comfort during hot summer days. The relaxed fit and attention to detail make these shorts a must-have addition to your summer wardrobe. Pair them with a classic white tee or a stylish button-down shirt for a look that''s both fashionable and easygoing. Experience the perfect blend of comfort and style with our "Ocean Breeze" Men''s Shorts - your go-to choice for a casual yet fancy summer look that sets you apart with a touch of sophistication.', 29.99, '/images/mens-ocean-breeze-shorts(kristino-boxers-djKkWGMahDI-unsplash).jpg', 2);

INSERT INTO product (product_name, product_description, product_price, product_image, category_id)
VALUES ('Men''s Black Sleeveless T-Shirt', 'Introducing our sleek and stylish Men''s Black Sleeveless T-Shirt, the epitome of effortless cool and comfort. Crafted from premium-quality, breathable fabric, this sleeveless tee is designed to keep you feeling fresh and confident throughout the day. The classic black hue adds a touch of sophistication to any casual look, making it a versatile addition to your wardrobe. The sleeveless design allows for unrestricted movement, making it the perfect choice for warm weather or layering under your favorite shirt or jacket. Whether you''re hitting the gym, strolling along the beach, or hanging out with friends, our Men''s Black Sleeveless T-Shirt effortlessly combines fashion and function. Dress it up with jeans and sneakers for a laid-back urban vibe or pair it with shorts for a relaxed summer look. Embrace the essence of timeless style with our Men''s Black Sleeveless T-Shirt and elevate your everyday outfits with a touch of modern elegance. Stay cool, comfortable, and effortlessly chic in this wardrobe essential that complements your active lifestyle.', 14.99, '/images/mens-sleeveless-tshirt(mubariz-mehdizadeh-Py8F6-hRn5o-unsplash).jpg', 2);

INSERT INTO product (product_name, product_description, product_price, product_image, category_id)
VALUES ('"Cobbles Classic" Men''s White T-Shirt', 'Introducing our "Cobbles Classic" Men''s White T-Shirt with a captivating Lighthouse Print Design. Embrace the timeless charm of this classic white tee, crafted with the perfect blend of comfort and style. The lighthouse print adds a touch of nautical inspiration, evoking visions of coastal adventures and tranquil seaside escapes. Made from premium-quality, soft fabric, the "Cobbles Classic" T-Shirt ensures you stay relaxed and at ease throughout the day. The pristine white color serves as a canvas for the artful lighthouse print, making this tee an eye-catching addition to your wardrobe. Whether you''re strolling along the boardwalk or exploring new horizons, our "Cobbles Classic" Men''s White T-Shirt complements any casual look with a touch of maritime elegance. Dress it up with chinos for a polished ensemble or keep it laid-back with your favorite shorts for a relaxed coastal vibe. Embrace the essence of coastal style and embark on a fashion journey that celebrates both tradition and adventure with our "Cobbles Classic" Men''s White T-Shirt. Elevate your everyday attire with this captivating lighthouse-inspired design, and let your outfit be a beacon of timeless charm and sophistication.', 19.99, '/images/mens-cobbles-classic-tshirt(sincerely-media-9ShY-Tq70Mc-unsplash).jpg', 2);

INSERT INTO product (product_name, product_description, product_price, product_image, category_id)
VALUES (' Men''s Black Zip-Up Hoodie', 'Introducing our Men''s Black Zip-Up Hoodie, the perfect blend of functionality and style. Crafted with weather-resistant material, this hoodie ensures you stay prepared for whatever the day brings. Embrace the comfort and versatility of this wardrobe essential, making it ideal for both casual outings and outdoor adventures. The sleek black design exudes a sense of timeless sophistication, allowing you to effortlessly elevate your everyday look. The convenient zip-up feature offers easy layering, making it an essential piece for any season. Whether you''re running errands, exploring nature, or simply relaxing with friends, our Men''s Black Zip-Up Hoodie keeps you looking effortlessly cool. Pair it with jeans and sneakers for a laid-back urban vibe or throw it over your workout gear for a sporty athleisure style. Embrace the fusion of fashion and function and embark on your daily ventures with confidence in our Men''s Black Zip-Up Hoodie, the ultimate companion for your active lifestyle.', 49.99, '/images/mens-zip-up-hoodie(stephanie-nakagawa-ADSKIn0ScDg-unsplash).jpg', 2);

INSERT INTO product (product_name, product_description, product_price, product_image, category_id)
VALUES ('Men''s Maroon Polo Shirt', 'Introducing our Men''s Maroon Polo Shirt with a charming White Dot Pattern, a perfect blend of classic style and modern sophistication. Crafted with precision, this polo shirt showcases a timeless maroon hue complemented by an elegant white dot pattern, adding a touch of flair to your wardrobe. Embrace the versatility of this shirt, effortlessly transitioning from casual to semi-formal occasions. The comfortable and breathable fabric ensures a relaxed fit, making it an ideal choice for any season. Whether you''re heading to a social gathering or a weekend getaway, our Men''s Maroon Polo Shirt with White Dot Pattern keeps you looking refined and polished. Pair it with chinos for a smart-casual ensemble or dress it down with shorts for a laid-back summer vibe. Embrace the essence of timeless fashion and elevate your style with our Men''s Maroon Polo Shirt, a statement piece that reflects your sophisticated taste and attention to detail.', 49.99, '/images/mens-maroon-polo(banjo-emerson-mathew-xWUT0etaVYw-unsplash).jpg', 2);

--Women's Fashion (5 to start)
INSERT INTO product (product_name, product_description, product_price, product_image, category_id)
VALUES ('Women''s Floral Blouse','Introducing our Women''s Floral Blouse, a beautiful blend of elegance and femininity. Embrace the enchanting allure of the floral pattern that gracefully adorns this blouse, bringing a touch of nature-inspired charm to your wardrobe. Crafted with meticulous attention to detail, this blouse is designed to accentuate your silhouette and provide a flattering fit. The lightweight and breathable fabric ensure comfort, making it a perfect choice for any occasion, from casual outings to special events. Whether you pair it with jeans for a chic daytime look or dress it up with a skirt for an evening affair, our Women''s Floral Blouse adds a dash of sophistication to your ensemble. Embrace the essence of effortless beauty and express your unique style with this captivating floral masterpiece. Elevate your wardrobe and revel in the grace and poise of our Women''s Floral Blouse, a timeless addition that celebrates the elegance of womanhood.', 39.99,'/images/womens-floural-blouse(dom-cMB3D5Ox5KE-unsplash).jpg', 3);

INSERT INTO product (product_name, product_description, product_price, product_image, category_id)
VALUES ('Women''s Red "Not Today" White Print T-Shirt','Introducing our Women''s Red "Not Today" White Print T-Shirt, a bold and sassy statement piece that embraces your empowered spirit. The vibrant red color exudes confidence, while the playful "Not Today" white print adds a touch of attitude and humor to your outfit. Crafted from soft and comfortable fabric, this t-shirt ensures a relaxed fit that keeps you feeling at ease throughout the day. Whether you''re conquering the world or simply enjoying some "me" time, this tee is the perfect expression of your mood. Pair it with jeans or shorts for a casual yet spirited look, or layer it under a jacket for added versatility. Embrace the essence of individuality and let your outfit speak volumes with our Women''s Red "Not Today" White Print T-Shirt, a stylish and empowering addition to your wardrobe. Show the world you''re in charge and ready to take on any challenge with this expressive and unapologetically confident t-shirt.', 19.99,'/images/womens-not-today-tshirt(josue-escoto-crsQ7CNIovw-unsplash).jpg', 3);

INSERT INTO product (product_name, product_description, product_price, product_image, category_id)
VALUES ('Women''s Highrise Denim Shorts','Introducing our Women''s Highrise Denim Shorts, a perfect blend of style and comfort for your summer adventures. Crafted with high-quality denim fabric, these shorts offer a flattering and form-fitting silhouette. The high-rise waist provides a chic and trendy look while offering a comfortable fit that hugs your curves in all the right places. Embrace the versatility of these shorts, as they effortlessly pair with a variety of tops for any occasion, from casual outings to beach days and beyond. The classic denim design adds a touch of timeless fashion to your wardrobe, making these shorts a staple piece for your warm-weather ensembles. Dress them up with a flowy blouse or keep it laid-back with a simple tee for a relaxed and stylish look. Embrace the essence of summer with our Women''s Highrise Denim Shorts, a fashion-forward addition that combines style and ease for the perfect summer outfit. Get ready to embrace the sun and enjoy endless style possibilities with these must-have denim shorts.', 39.99, '/images/womens-denim-shorts(arun-sharma-frb_45xkKlM-unsplash).jpg', 3);

INSERT INTO product (product_name, product_description, product_price, product_image, category_id)
VALUES ('Women''s Black Dress with Flowers','Introducing our Women''s Black Dress with Flowers, a captivating blend of sophistication and floral charm. This exquisite dress showcases a timeless black hue, complemented by a delicate floral pattern, adding a touch of feminine elegance to your ensemble. Crafted with meticulous attention to detail, the dress features a figure-flattering silhouette that accentuates your curves and exudes confidence. The lightweight and breathable fabric ensures comfort, making it an ideal choice for any special occasion, from romantic evenings to garden parties. Whether you pair it with heels for a glamorous look or opt for sandals to keep it casual chic, our Women''s Black Dress with Flowers is a statement piece that stands out in any crowd. Embrace the essence of grace and allure with this enchanting floral dress, and let your style bloom with beauty and poise. Elevate your wardrobe and embrace the beauty of nature-inspired fashion with our Women''s Black Dress with Flowers, an exquisite addition that leaves a lasting impression.', 54.99,'/images/womens-black floural-dress(pietra-schwarzler-lSLq_xQdFNI-unsplash).jpg', 3);

INSERT INTO product (product_name, product_description, product_price, product_image, category_id)
VALUES ('Women''s Black Pants and Blazer Set','Introducing our Women''s Black Pants and Blazer Set, a sophisticated ensemble that exudes timeless elegance and versatility. The set features a pair of impeccably tailored black pants, offering a flattering and polished fit that flatters your figure. Paired with the matching black blazer, this ensemble creates a powerful and chic look suitable for any professional setting or formal occasion. Crafted with high-quality fabric, the pants and blazer offer comfort and ease of movement, ensuring you feel confident and poised throughout the day. Whether you''re attending a business meeting, a formal event, or simply want to elevate your everyday style, this black pants and blazer set is a must-have addition to your wardrobe. Embrace the essence of refined fashion and embrace the endless possibilities of mixing and matching these wardrobe staples with various tops and accessories for a fresh and sophisticated look every time. Elevate your wardrobe with our Women''s Black Pants and Blazer Set, the epitome of elegance and versatility, and step into the world of timeless fashion with confidence and grace.', 129.99,'/images/womens-black suit-set(nassim-boughazi-dodzmVtjoKs-unsplash).jpg', 3);

--girls' fashion (5 to start)
INSERT INTO product (product_name, product_description, product_price, product_image, category_id)
VALUES ('Girls'' Teal Plaid Button-Up Top', 'Introducing our Girls'' Teal Plaid Button-Up Top, a delightful blend of charm and style for your young fashionista. This eye-catching top features a beautiful teal plaid pattern, adding a playful and vibrant touch to her wardrobe. Crafted with soft and comfortable fabric, this button-up top ensures she stays at ease throughout her daily adventures. The versatile design allows for easy pairing with jeans, shorts, or skirts, making it a versatile piece for various occasions. Whether she''s exploring new places or attending a special event, our Girls'' Teal Plaid Button-Up Top keeps her looking effortlessly chic and confident. Embrace the essence of youthful fashion and let her express her unique style with this adorable plaid top, the perfect addition to her growing wardrobe. Elevate her outfits with a dash of color and a pinch of fun, and let her shine in the beauty of our Girls'' Teal Plaid Button-Up Top.', 29.99, '/images/girls-plaid-top(angel-balashev-HBEfd-au2is-unsplash).jpg', 4);

INSERT INTO product (product_name, product_description, product_price, product_image, category_id)
VALUES ('Girls'' White Athletic Tank-Top', 'Introducing our Girls'' White Athletic Tank-Top, the perfect blend of comfort and style for your active young one. This tank-top is crafted with high-quality, breathable fabric, ensuring she stays cool and comfortable during her sports and fitness activities. The classic white color adds a touch of simplicity and versatility, allowing for easy pairing with various bottoms and sportswear. The athletic design provides unrestricted movement, making it an ideal choice for running, playing, or any physical activity she enjoys. Whether she''s on the field, at the gym, or simply enjoying outdoor fun, our Girls'' White Athletic Tank-Top keeps her looking sporty and feeling confident. Embrace the essence of active fashion and let her embrace her active lifestyle with this essential tank-top, the perfect companion for her energetic adventures. Elevate her sports attire with this comfortable and stylish tank-top, ensuring she stays motivated and ready to conquer any challenge with ease.', 19.99,'/images/girls-athletic-tank(bewakoof-com-official-mtOMSpOWxRI-unsplash).jpg', 4);

INSERT INTO product (product_name, product_description, product_price, product_image, category_id)
VALUES ('Girls'' Bananna Patern Top', 'Introducing our delightful girls'' white top, adorned with a charming banana pattern that exudes playful elegance. Crafted with care from high-quality materials, this top is as comfortable as it is stylish, making it the perfect addition to any little fashionista''s wardrobe. The white background beautifully complements the cheerful banana motif, creating a cheerful and versatile design that can be paired with jeans, skirts, or shorts for a variety of chic and casual looks. Whether for a day at the park or a special occasion, our banana pattern top promises to bring joy and charm to any outfit.', 14.99,'/images/girls-banana-pattern-top(annie-spratt-1Jg-_nekJT0-unsplash).jpg', 4);

INSERT INTO product (product_name, product_description, product_price, product_image, category_id)
VALUES ('Girls'' Blue Dress', 'Introducing our Girls'' Blue Dress, a charming and versatile addition to your little one''s wardrobe. This delightful dress features a lovely shade of blue, adding a touch of elegance to her outfits. Crafted with care and attention to detail, the dress offers a comfortable and perfect fit for your young fashionista. The classic design and soft fabric ensure she stays at ease during her special occasions, from birthday parties to family gatherings. Whether she''s twirling on the dance floor or enjoying playtime with friends, our Girls'' Blue Dress keeps her looking adorable and confident. Embrace the essence of youthful fashion and let her shine in the beauty of this charming dress, perfect for creating cherished memories. Elevate her style with this lovely blue dress, designed to make her feel like the star of every occasion, and let her imagination and joy run wild in our Girls'' Blue Dress, made for creating magical moments.', 39.99,'/images/girls-blue-dress(senjuti-kundu-GCI8dqi4uWM-unsplash).jpg', 4);

INSERT INTO product (product_name, product_description, product_price, product_image, category_id)
VALUES ('Girls'' Colorful Floral Pattern Top', 'Presenting our Girls'' Colorful Floral Pattern Top, a vibrant and charming addition to any young fashionista''s wardrobe. This delightful top features a captivating floral pattern, bursting with an array of cheerful hues that exude playful elegance. Crafted with attention to detail and comfort in mind, this stylish piece ensures a delightful wearing experience for every occasion. The colorful floral design beautifully complements various bottoms, from jeans to skirts, allowing for versatile and chic outfit combinations. Whether for a casual outing with friends or a special family event, our Colorful Floral Pattern Top promises to brighten up any day with its joyful and feminine appeal.', 24.99,'/images/girls-colorful-floural-pullover(priscilla-du-preez-3CTufp-cpzo-unsplash).jpg', 4);


--boy's fashion
INSERT INTO product (product_name, product_description, product_price, product_image, category_id)
VALUES ('Boy''s Black "Skip School Make Money" Pullover Hoodie', 'Introducing our Boy''s Black "Skip School Make Money" Pullover Hoodie, a cool and edgy statement piece for your young trendsetter. This hoodie showcases a bold "Skip School Make Money" slogan in white, adding a touch of rebellious charm to his wardrobe. Crafted with high-quality fabric, this pullover hoodie ensures he stays cozy and comfortable all day long. The classic black color provides a versatile and stylish look that complements any outfit. The pullover design with a hoodie offers a relaxed fit, making it perfect for casual outings or hanging out with friends. Whether he''s exploring the neighborhood or simply having fun, our Boy''s Black "Skip School Make Money" Pullover Hoodie keeps him looking effortlessly cool. Embrace the essence of youthful fashion and let him express his individuality with this standout hoodie, the perfect addition to his streetwear collection. Elevate his style with a touch of attitude and let him shine in the confidence of our Boy''s Black "Skip School Make Money" Pullover Hoodie, designed to make a bold statement and inspire his creativity and self-expression.', 39.99,'/images/boys-black-hoodie(ben-den-engelsen-eNyXK17so6A-unsplash).jpg', 5);

INSERT INTO product (product_name, product_description, product_price, product_image, category_id)
VALUES (' Boy''s Grey Knit Sweater', 'Introducing our Boy''s Grey Knit Sweater, a cozy and stylish essential for chilly days. This classic grey sweater is crafted with a soft and comfortable knit fabric, ensuring he stays warm and snug throughout the season. The versatile grey color complements any outfit, making it a versatile piece for various occasions. Whether he''s heading to school, spending time with family, or playing outdoors, our Boy''s Grey Knit Sweater keeps him looking effortlessly cool and ready for any adventure. The sweater features a classic design with a relaxed fit, allowing for easy layering over his favorite shirts or t-shirts. Embrace the essence of timeless fashion and let him stay fashionably warm with this versatile knit sweater, the perfect addition to his winter wardrobe. Elevate his style with this cozy and chic sweater, designed to keep him both comfortable and fashion-forward in any setting.', 49.99, '/images/boys-grey-knit-sweater(annie-spratt-1lEMMQsaeLI-unsplash).jpg', 5);

INSERT INTO product (product_name, product_description, product_price, product_image, category_id)
VALUES ('Boy''s Plaid Shorts', 'Introducing our Boys'' Plaid Shorts, a perfect blend of style and comfort for your little adventurer. These classic shorts feature a timeless plaid pattern that adds a touch of charm to any outfit. Crafted with attention to quality and durability, they are designed to withstand the playful activities of young boys while keeping them comfortable all day long. The versatile plaid design allows for effortless pairing with various tops, making them ideal for casual playdates or family outings. Whether strolling at the park or exploring new adventures, our Boys'' Plaid Shorts ensure your little one looks sharp and feels at ease throughout the day.', 14.99, '/images/boys-plaid-shorts(tim-mossholder-elXAqki7yA4-unsplash).jpg', 5);

INSERT INTO product (product_name, product_description, product_price, product_image, category_id)
VALUES ('Boy''s Denim Jeans', 'Introducing our Boy''s Denim Jeans, a timeless and versatile staple for his everyday wardrobe. These classic denim jeans are crafted with high-quality fabric, ensuring durability and comfort for his active lifestyle. The deep indigo color adds a touch of style to any outfit, making them a perfect match for casual or semi-formal occasions. The jeans feature a relaxed fit with a straight-leg design, offering ease of movement and a comfortable fit for all-day wear. Whether he''s playing with friends, attending school, or spending time with family, our Boy''s Denim Jeans keep him looking effortlessly cool and ready for any adventure. Embrace the essence of timeless fashion and let him express his unique style with these versatile denim jeans, a wardrobe essential that never goes out of style. Elevate his outfits with this classic piece, designed to provide both comfort and fashion-forward flair for his daily endeavors.', 29.99, '/images/boys-denim-jeans(alex-gorin-LBM_-1X6Z2Q-unsplash).jpg', 5);

INSERT INTO product (product_name, product_description, product_price, product_image, category_id)
VALUES ('Boy''s Red Knit Sweater', 'Introducing our Boy''s Red Knit Sweater, a cozy and vibrant addition to his winter wardrobe. This charming red sweater is crafted with a soft and comfortable knit fabric, ensuring he stays warm and stylish during colder days. The eye-catching red color adds a pop of energy to his outfit, making him stand out with confidence. The sweater features a classic design with a relaxed fit, providing both comfort and ease of movement for his active days. Whether he''s heading to school, spending time with family, or enjoying outdoor fun, our Boy''s Red Knit Sweater keeps him looking effortlessly cool and ready for any winter adventure. Embrace the essence of warmth and style with this vibrant knit sweater, the perfect companion for his winter escapades. Elevate his winter outfits with this cozy and chic sweater, designed to keep him both comfortable and fashion-forward in any setting. Let him embrace the joy of the season and showcase his unique style with our Boy''s Red Knit Sweater, a standout piece that adds warmth and vibrancy to his winter looks.', 49.99, '/images/boys-red-knit-sweater(whereslugo-UquTB_Opzqg-unsplash).jpg', 5);

--electronics
INSERT INTO product (product_name, product_description, product_price, product_image, category_id)
VALUES ('Black Over-Ear Multimedia Headphones', 'Introducing our Black Over-Ear Multimedia Headphones, the perfect companion for your immersive audio experience. These sleek and stylish headphones are designed for ultimate comfort and exceptional sound quality. The over-ear design provides superior noise isolation, allowing you to dive deep into your favorite music, movies, and games without distractions. The versatile black color complements any outfit and adds a touch of sophistication to your audio gear. Crafted with precision, these headphones deliver clear and rich sound, ensuring every beat and note is delivered with precision and clarity. The adjustable headband and cushioned ear cups guarantee a comfortable fit, even during extended listening sessions. Whether you''re on a long journey, working from home, or simply relaxing, our Black Over-Ear Multimedia Headphones provide the perfect audio companion. Equipped with advanced multimedia features, these headphones come with built-in controls for volume adjustment and play/pause functions, ensuring seamless control of your audio content. The foldable design makes them convenient to carry and store, making them the ideal travel companion. Embrace the essence of superior audio performance and style with our Black Over-Ear Multimedia Headphones, designed to elevate your listening experience to new heights. Immerse yourself in a world of exceptional sound and enjoy your favorite content like never before with these cutting-edge headphones.', 69.99, '/images/electronics-black-earphones(tomasz-gawlowski-YDZPdqv3FcA-unsplash).jpg', 1);

INSERT INTO product (product_name, product_description, product_price, product_image, category_id)
VALUES ('Funky Backlit Mechanical Keyboard', 'Introducing our Funky Backlit Mechanical Keyboard, a perfect choice for electronics enthusiasts seeking a unique and stylish typing experience. This mechanical keyboard combines fun and functionality with its vibrant backlit design that adds a touch of personality to your workspace. The sturdy build and satisfying tactile feedback of the mechanical keys ensure durability and seamless typing for years to come. Whether you''re a gamer, programmer, or content creator, this keyboard is a must-have for anyone seeking an extraordinary and expressive typing experience. Upgrade your setup with this funky and reliable mechanical keyboard, and let your creativity and productivity shine through every keystroke.', 79.99, '/images/electronics-funky-keyboard(jay-zhang-2MCF_5fdcnU-unsplash).jpg', 1);

INSERT INTO product (product_name, product_description, product_price, product_image, category_id)
VALUES ('Wireless Mouse', 'Introducing our Wireless Mouse, the ultimate companion for seamless and clutter-free computing. This sleek and ergonomic wireless mouse is designed for precision and ease of use, making it a perfect fit for both work and play. Say goodbye to tangled cables and enjoy the freedom of wireless connectivity as you navigate through your tasks with precision and accuracy. Crafted with advanced technology, the wireless mouse offers smooth and responsive tracking on various surfaces, providing a seamless user experience. The comfortable grip and ergonomic design ensure reduced strain on your hand during extended use, making it ideal for long hours of productivity. The wireless mouse comes with a reliable battery life, saving you from frequent replacements, and its compact design makes it a travel-friendly accessory for those on the go. Whether you''re working on spreadsheets, editing photos, or gaming, our Wireless Mouse delivers exceptional performance and responsiveness, enhancing your overall computing experience. Embrace the essence of convenience and productivity with our Wireless Mouse, a versatile and reliable companion that complements any electronics setup. Upgrade your computing experience with this wireless marvel, and enjoy the freedom of untethered navigation as you accomplish your tasks with efficiency and ease.', 59.99, '/images/electronics-wireless-mouse(oscar-ivan-esquivel-arteaga-ZtxED1cpB1E-unsplash).jpg', 1);

INSERT INTO product (product_name, product_description, product_price, product_image, category_id)
VALUES ('Ultra-Wide Curved Monitor', 'Introducing our Ultra-Wide Curved Monitor, a pinnacle of immersive viewing for your electronics setup. This cutting-edge monitor boasts a sleek and contemporary design, featuring an ultra-wide curved display that wraps around your field of vision, pulling you into the heart of your content. With its expansive screen real estate, you can enjoy multitasking like never before, simultaneously working on projects, streaming videos, and gaming, all on a single monitor. Crafted with advanced display technology, this monitor delivers stunning visuals with vibrant colors and sharp details, ensuring an unparalleled viewing experience. The curved design not only enhances visual immersion but also minimizes eye strain, allowing you to work or play for extended periods with comfort. Designed to meet the demands of professionals, gamers, and content creators alike, our Ultra-Wide Curved Monitor offers a high refresh rate and quick response time, delivering fluid graphics and seamless motion. The versatile connectivity options and adjustable stand provide added convenience and adaptability to your workspace. Upgrade your viewing experience with this state-of-the-art monitor and embrace the essence of next-level immersion and productivity.', 829.99, '/images/electronics-ultrawide-monitor(petri-r-6j_lmeycTrM-unsplash).jpg', 1);

INSERT INTO product (product_name, product_description, product_price, product_image, category_id)
VALUES ('Universal Device Remote Control', 'Introducing our Universal Device Remote Control, the ultimate all-in-one solution to simplify your electronics experience. This versatile remote control is designed to seamlessly integrate with multiple devices, providing effortless control over your TV, DVD player, audio system, and more. Say goodbye to juggling multiple remotes and enjoy the convenience of one remote to rule them all. Crafted with advanced technology, our Universal Device Remote Control features intuitive programming and a user-friendly interface, making setup a breeze. The ergonomic design ensures a comfortable grip, and the well-organized buttons allow for easy navigation and quick access to your favorite functions. Upgrade your remote control experience and simplify your life with this versatile and user-friendly device, designed to enhance your everyday entertainment enjoyment. Take control of your electronics with ease and let our Universal Device Remote Control be your reliable companion in managing all your devices efficiently.', 29.99, '/images/electronics-universal-remote(erik-mclean-U-Vu_r6qyyU-unsplash).jpg', 1);
